package Model;
// Generated Nov 13, 2017 2:08:37 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Isachchu generated by hbm2java
 */
public class Isachchu extends Model.iSach implements java.io.Serializable {

     private boolean coBanCung;
     private Set noidungs = new HashSet(0);

    public Isachchu() {
    }

	
    public Isachchu(Bientap bientap, Tacgia tacgia, Theloaisach theloaisach, String ten, String anhBia, String tomTat, String linkDown, String mucLuc, boolean coBanCung, Date ngayTao, Date ngayCapNhat) {
        super(linkDown, mucLuc, bientap, tacgia, theloaisach, ten, anhBia, tomTat, ngayTao, ngayCapNhat);
        this.coBanCung = coBanCung;
    }
    public Isachchu(Bientap bientap, Tacgia tacgia, Theloaisach theloaisach, String ten, String anhBia, String tomTat, String linkDown, String mucLuc, boolean coBanCung, Date ngayTao, Date ngayCapNhat, Set noidungs) {
       super(linkDown, mucLuc, bientap, tacgia, theloaisach, ten, anhBia, tomTat, ngayTao, ngayCapNhat);
       this.coBanCung = coBanCung;
       this.noidungs = noidungs;
    }
    
    public boolean isCoBanCung() {
        return this.coBanCung;
    }
    
    public void setCoBanCung(boolean coBanCung) {
        this.coBanCung = coBanCung;
    }
    public Set getNoidungs() {
        return this.noidungs;
    }
    
    public void setNoidungs(Set noidungs) {
        this.noidungs = noidungs;
    }

}


