package Model;
// Generated Nov 13, 2017 2:08:37 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Isachnoi generated by hbm2java
 */
public class Isachnoi extends Model.iSach implements java.io.Serializable {

     private int nguoiDoc;
     private Nguoidoc vitualNguoiDoc;

    public Nguoidoc getVitualNguoiDoc() {
        return vitualNguoiDoc;
    }

    public void setVitualNguoiDoc(Nguoidoc vitualNguoiDoc) {
        this.vitualNguoiDoc = vitualNguoiDoc;
    }
     private Set nguoidocs = new HashSet(0);

    public Isachnoi() {
    }

	
    public Isachnoi(Bientap bientap, Tacgia tacgia, Theloaisach theloaisach, String ten, String anhBia, String tomTat, String mucLuc, int nguoiDoc, String linkDown, Date ngayTao, Date ngayCapNhat) {
        super(linkDown, mucLuc, bientap, tacgia, theloaisach, ten, anhBia, tomTat, ngayTao, ngayCapNhat);
        this.nguoiDoc = nguoiDoc;

    }
    public Isachnoi(Bientap bientap, Tacgia tacgia, Theloaisach theloaisach, String ten, String anhBia, String tomTat, String mucLuc, int nguoiDoc, String linkDown, Date ngayTao, Date ngayCapNhat, Set nguoidocs) {
       super(linkDown, mucLuc, bientap, tacgia, theloaisach, ten, anhBia, tomTat, ngayTao, ngayCapNhat);
       this.nguoiDoc = nguoiDoc;
       this.nguoidocs = nguoidocs;
    }

    public int getNguoiDoc() {
        return this.nguoiDoc;
    }
    
    public void setNguoiDoc(int nguoiDoc) {
        this.nguoiDoc = nguoiDoc;
    }

    public Set getNguoidocs() {
        return this.nguoidocs;
    }
    
    public void setNguoidocs(Set nguoidocs) {
        this.nguoidocs = nguoidocs;
    }

}


