package Model;
// Generated Nov 13, 2017 2:08:37 PM by Hibernate Tools 4.3.1



/**
 * Noidung generated by hbm2java
 */
public class Noidung  implements java.io.Serializable {


     private Integer id;
     private Isachchu isachchu;
     private String tenChuong;
     private String noiDung;

    public Noidung() {
    }

    public Noidung(Isachchu isachchu, String tenChuong, String noiDung) {
       this.isachchu = isachchu;
       this.tenChuong = tenChuong;
       this.noiDung = noiDung;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Isachchu getIsachchu() {
        return this.isachchu;
    }
    
    public void setIsachchu(Isachchu isachchu) {
        this.isachchu = isachchu;
    }
    public String getTenChuong() {
        return this.tenChuong;
    }
    
    public void setTenChuong(String tenChuong) {
        this.tenChuong = tenChuong;
    }
    public String getNoiDung() {
        return this.noiDung;
    }
    
    public void setNoiDung(String noiDung) {
        this.noiDung = noiDung;
    }




}


